import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <Sidebar />
        <div className="pl-[240px] min-h-dvh">
          <header className="sticky top-0 z-30 h-14 border-b bg-white/80 backdrop-blur flex items-center px-4">
            <div className="text-sm text-gray-500">Embedded App</div>
          </header>
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
